### ISSUE TITLE
Can't install to Octoprint 1.6.1, Python version error. 

### ISSUE THREAD

**Issue by TalkieToaster86** [appdevelopmentandsuch/Thingiverse-Downloader#12]
"ERROR: Package 'thingiverse-downloader' requires a different Python: 2.7.16 not in '>=3, <4'"

Is there any way for me to work around this? I know NOTHING about code.

**Comment by pete-oconnell** [comment]
@TalkieToaster86 You need to upgrade it via Octopi - https://octoprint.org/blog/2020/09/10/upgrade-to-py3/

**Comment by appdevelopmentandsuch** [comment]
Thanks @pete-oconnell !

**Comment by pete-oconnell** [comment]
no worries - can you fix your profile image though? It triggers some kind
of OCD in me! :)
